# Generated by Django 4.2.3 on 2026-07-12 08:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.CharField(choices=[('order', 'Proses Order'), ('restock', 'Restock'), ('reply_chat', 'Balas Chat'), ('packing', 'Packing'), ('custom', 'Custom Task'), ('other', 'Lainnya')], default='other', max_length=50),
        ),
        migrations.CreateModel(
            name='CustomTaskTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('priority', models.CharField(choices=[('urgent', 'Urgent'), ('normal', 'Normal'), ('low', 'Low')], default='normal', max_length=20)),
                ('recurrence_type', models.CharField(choices=[('daily', 'Setiap Hari'), ('weekly', 'Pilih Hari Dalam Seminggu'), ('monthly_end', 'Akhir Bulan')], default='daily', max_length=20)),
                ('weekly_days', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_task_templates', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='custom_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.customtasktemplate'),
        ),
    ]
