# Generated by Django 4.2.3 on 2026-07-11 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('extraction', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtractionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_ai_response', models.JSONField(blank=True, null=True)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
                ('screenshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='extraction.screenshot')),
            ],
        ),
        migrations.CreateModel(
            name='ExtractedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=300)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True)),
                ('status', models.CharField(choices=[('perlu_tindakan', 'Perlu Tindakan'), ('diproses', 'Diproses'), ('selesai', 'Selesai'), ('dikirim', 'Dikirim'), ('dibatalkan', 'Dibatalkan'), ('lainnya', 'Lainnya')], default='lainnya', max_length=30)),
                ('order_id', models.CharField(blank=True, max_length=100, null=True)),
                ('buyer_name', models.CharField(blank=True, max_length=200, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('confidence', models.FloatField(default=0.0)),
                ('is_verified', models.BooleanField(default=False)),
                ('extraction_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='extraction.extractionresult')),
                ('matched_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extracted_items', to='catalog.product')),
            ],
        ),
    ]
