# Generated by Django 4.2.3 on 2026-07-12 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extraction', '0002_extractionresult_extracteditem'),
    ]

    operations = [
        migrations.AddField(
            model_name='extractionresult',
            name='narrative',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='screenshot',
            name='tag',
            field=models.CharField(choices=[('order_list', 'Daftar Pesanan'), ('order_detail', 'Detail Pesanan'), ('product_stock', 'Stok Produk'), ('chat', 'Chat Pelanggan')], default='order_list', max_length=50),
        ),
    ]
